In [5]:
#1
import numpy as np
while True:
    try:
        length=int(input("enter the length on input vector: "))
    except:
        print("Error:expected an integer")
        
    else:
        break
print('\n')
while True:
    try:
        print("Please provide elements for a 1D numeric array")
        input_array=np.array([float(input("Enter a number :")) for i in range(length)])
        break
    except:
        print("All the elements of the list should be numbers")
print('\n')
while True:
    print("How do you want the order of powers in Vandermonde matrix to be (1)if ascending enter: True \
    (2) id descending enter: False")
    order=input("Do you want the order to be ascending? True or False? ")
    if order in ["True","False"]:
        order=bool(order)
        break
    else:
        print("Error:enter either True or False")
print('\n')# To provide a gap between the two input blocks
while True:
    try:
        N=int(input("Enter the number of columns you want in Vandermonde matrix :"))
        break
    except:
        print("Error: expected an integer")
    
def Matrix_Vandermonde(vector,n=length,increasing=False):
    Vandermonde_mat=vector
    for i in range(1,n):
        Vandermonde_mat=np.column_stack((Vandermonde_mat,vector)) 
        #print(df_initial
    for i in range(n):
        if increasing==True:
            Vandermonde_mat[:,i]=Vandermonde_mat[:,i]**i
        elif increasing==False:
            Vandermonde_mat[:,i]=Vandermonde_mat[:,i]**(n-i-1)
    return np.matrix(Vandermonde_mat)

print("The resultant Vandermonde matrix is : \n",Matrix_Vandermonde(vector=input_array,n=N,increasing=order))
print('\n\n')
print("The resultant Vandermonde matrix is : \n", Matrix_Vandermonde(vector=input_array,increasing=order)) 
print('\n\n')
print("The resultant Vandermonde matrix is : \n",Matrix_Vandermonde(vector=input_array,n=N)) #order is not specified
print('\n\n')
print("The resultant Vandermonde matrix is : \n",Matrix_Vandermonde(vector=input_array))


enter the length on input vector: 4


Please provide elements for a 1D numeric array
Enter a number :1
Enter a number :2
Enter a number :3
Enter a number :4


How do you want the order of powers in Vandermonde matrix to be (1)if ascending enter: True     (2) id descending enter: False
Do you want the order to be ascending? True or False? True


Enter the number of columns you want in Vandermonde matrix :5
The resultant Vandermonde matrix is : 
 [[  1.   1.   1.   1.   1.]
 [  1.   2.   4.   8.  16.]
 [  1.   3.   9.  27.  81.]
 [  1.   4.  16.  64. 256.]]



The resultant Vandermonde matrix is : 
 [[ 1.  1.  1.  1.]
 [ 1.  2.  4.  8.]
 [ 1.  3.  9. 27.]
 [ 1.  4. 16. 64.]]



The resultant Vandermonde matrix is : 
 [[  1.   1.   1.   1.   1.]
 [ 16.   8.   4.   2.   1.]
 [ 81.  27.   9.   3.   1.]
 [256.  64.  16.   4.   1.]]



The resultant Vandermonde matrix is : 
 [[ 1.  1.  1.  1.]
 [ 8.  4.  2.  1.]
 [27.  9.  3.  1.]
 [64. 16.  4.  1.]]


In [4]:
#2
import numpy as np

while True:
    try:
        n=int(input("Enter the length of desired sequence :")) 
    except:
        print("Error: length of sequence should be an integer")
        continue
    try:
        k=int(input("Desired window size :")) 
    except:
        print("Error: window size should be an integer")
        continue
        
    if n>0 and k<=n:
        break
    elif n<=0:
        print("Error: length of sequence should be greater than 0")
        continue
    elif k>n:
        print("Error: window size should not be greater than length of the sequence")
        continue

while True:
    try:
        seq=[float(input("Provide the values for the sequence :")) for i in range(n)]
    except:
        print("Error: All elements to the sequence should be numbers")
    else:
        break
def moving_average(sequence, n=1) :
    ret = np.cumsum(sequence, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

print("\n\n","Output 1 \n","-"*90)
print("Moving average from input values :",moving_average(seq,k))


Enter the length of desired sequence :10
Desired window size :4
Provide the values for the sequence :10
Provide the values for the sequence :20
Provide the values for the sequence :30
Provide the values for the sequence :40
Provide the values for the sequence :50
Provide the values for the sequence :60
Provide the values for the sequence :70
Provide the values for the sequence :80
Provide the values for the sequence :90
Provide the values for the sequence :100


 Output 1 
 ------------------------------------------------------------------------------------------
Moving average from input values : [25. 35. 45. 55. 65. 75. 85.]
